# Generated by Django 5.0.6 on 2024-07-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='origen',
            field=models.CharField(default='software', max_length=50),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo_cambio',
            field=models.CharField(choices=[('agregar', 'Agregar'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar')], default='agregar', max_length=10),
        ),
    ]
