# Generated by Django 5.0.6 on 2024-09-12 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificacion_origen_notificacion_tipo_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=5),
        ),
        migrations.CreateModel(
            name='NotificacionEliminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionModificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad_anterior', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('nueva_prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificacion')),
            ],
        ),
    ]
