# Generated by Django 5.0.6 on 2024-09-12 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificacion_prioridad_notificacioneliminada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioneliminada',
            name='fecha_eliminacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
