# Generated by Django 5.0.6 on 2024-09-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificacioneliminada_fecha_eliminacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=100)),
                ('fecha_adquisicion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('fecha_instalacion', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='notificacion',
            name='hardware',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.hardware'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='software',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.software'),
        ),
    ]
