# Generated by Django 5.0.6 on 2024-09-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_hardware_software_notificacion_hardware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.hardware'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.software'),
        ),
    ]
