# Generated by Django 5.0.6 on 2024-09-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificacion_hardware_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='software',
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
    ]
