# Generated by Django 5.0.6 on 2024-11-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_accionregistro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccionRegistro',
        ),
    ]
